### ISSUE TITLE
Users not added to the server: I still have this exact issue, running the latest version of Wizarr (docker).

### ISSUE THREAD

**Issue by gerryflux** [wizarrrr/wizarr#331] opened 2024-01-20 07:01 UTC
I still have this exact issue, running the latest version of Wizarr (docker).

_Originally posted by @gerryflux in https://github.com/wizarrrr/wizarr/issues/281#issuecomment-1901815666_

**Comment by elmak** [comment] 2024-01-30 01:51
If you have a trailing / in your server url for the media server address, this failure occurs. Remove the trailing slash and suddenly everything works flawlessly. It would be a good idea to check and correct this issue seamlessly behind the scenes when validating.

**Comment by gerryflux** [comment] 2024-03-26 15:06
I can confirm that's not the issue
The connection to Plex works fine, it can scan and identify the libraries.
![image](https://github.com/wizarrrr/wizarr/assets/52464120/f0e21619-b747-4499-9a68-7b7b9dec4255)

**Comment by elmak** [comment] 2024-03-26 22:39
With the trailing slash I was able to connect Wizarr to Plex, scan the libraries, etc. Everything *appeared* to work, but invites would consistently fail. Removing the trailing slash solved that issue for me.

**Comment by ELKER54** [comment] 2024-04-21 11:49
I'm also having this issue. Did you manage to get it sorted?

**Comment by JamsRepos** [comment] 2024-04-21 12:07
If you're having this issue then you must have an issue with your Plex Token. Please ensure you're grabbing the correct Plex Token and not a temporary one. This is a very small case issue which can be rectified by yourself.

Like mentioned, check you don't have a trailing slash, this issue has been fixed on the beta branch. Any other issues caused by inviting is most likely an incorrect Plex Token. 

Please read the official Plex documenation: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

They also detail "Getting a New Token" which occurs for some users, not most.

**Comment by ELKER54** [comment] 2024-04-21 12:09
I use jellyfin not plex and don't have a trailing slash

**Comment by JamsRepos** [comment] 2024-04-21 12:10
> I use jellyfin not plex and don't have a trailing slash

Then this issue does not apply to you. Reach out on Discord and i'll assist.

**Comment by ELKER54** [comment] 2024-04-21 12:11
Will do

**Closed** 2024-04-29 21:08 UTC
